// GENERATED by `bun scripts/import-xcf.ts art/walking.xcf` — do not edit.
//
// Source of truth is art/walking.xcf. Change the artwork there, re-run the import,
// and commit both this file and the assets under public/hero/.

export type HeroLayer = {
  /** Slug from the GIMP layer name; the handle CSS and markup hook onto. */
  slug: string;
  /** The layer name as it reads in GIMP, for anyone diffing the two. */
  name: string;
  src: string;
  /** Position and width as percentages of the canvas, in paint order. */
  left: string;
  top: string;
  width: string;
};

/** Intrinsic size of the GIMP canvas; the hero uses it as an aspect ratio. */
export const HERO_CANVAS = { width: 2768, height: 1848 };

export const HERO_LAYERS: HeroLayer[] = [
  {
    slug: "walking",
    name: "walking.jpg",
    src: "/hero/walking.jpg",
    left: "0.0000%",
    top: "0.0000%",
    width: "100.0000%",
  },
  {
    slug: "head",
    name: "head",
    src: "/hero/head.png",
    left: "57.9480%",
    top: "22.1861%",
    width: "9.9350%",
  },
  {
    slug: "jaw",
    name: "jaw",
    src: "/hero/jaw.png",
    left: "58.5260%",
    top: "34.0368%",
    width: "2.9986%",
  },
];
